# Generated by Django 5.1.6 on 2025-02-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_cartitem_product_cartitem_fruit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
