# Generated by Django 5.1.6 on 2025-02-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
