# Generated by Django 5.1.6 on 2025-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_rename_created_at_contactmessage_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
