# Generated by Django 5.1.6 on 2025-02-24 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_fruititem_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.pulse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='fruit',
        ),
        migrations.DeleteModel(
            name='FruitItem',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
