# Generated by Django 5.1.6 on 2025-02-24 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_wishlist_remove_cartitem_fruit_delete_fruititem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='fruit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.fruit'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='pulse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.pulse'),
        ),
    ]
