# Generated by Django 5.1.6 on 2025-02-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_wishlist_fruit_alter_wishlist_pulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='vegie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.vegie'),
        ),
    ]
