# Generated by Django 5.1.6 on 2025-02-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_fruititem_pulseitem_shoppingcart_vegetableitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('product_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='vegetable',
        ),
        migrations.DeleteModel(
            name='FruitItem',
        ),
        migrations.DeleteModel(
            name='PulseItem',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='VegetableItem',
        ),
    ]
