# Generated by Django 5.1.6 on 2025-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_remove_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.TextField(default='[]'),
        ),
    ]
