# Generated by Django 5.1.6 on 2025-03-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_order_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Farm Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='farm_photos/', verbose_name='Farm Photo')),
                ('video', models.FileField(blank=True, null=True, upload_to='farm_videos/', verbose_name='Farm Video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.JSONField(default=list),
        ),
    ]
