# Generated by Django 5.1.6 on 2025-03-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_myfarm_alter_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfarm',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farm_photos/', verbose_name='Farm Photo'),
        ),
    ]
