# Generated by Django 5.1.6 on 2025-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_alter_myfarm_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfarm',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='myfarm',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='farm_photos/', verbose_name='Farm Photo'),
        ),
        migrations.AddField(
            model_name='myfarm',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='farm_photos/', verbose_name='Farm Photo'),
        ),
    ]
