# Generated by Django 5.1.6 on 2025-03-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_coupon_alter_cart_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_type',
            field=models.CharField(max_length=50),
        ),
    ]
