# Generated by Django 5.1.6 on 2025-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_remove_coupon_created_at_remove_coupon_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_amount',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
