# Generated by Django 5.1.6 on 2025-03-16 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_order_coupon_code_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Farm Title', max_length=200)),
                ('photos11', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='cow_photos/')),
                ('description', models.TextField(default='Default description')),
                ('photos12', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='cow_photos/')),
                ('video', models.FileField(blank=True, default='default_video.mp4', null=True, upload_to='cow_videos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Farm Title', max_length=200)),
                ('photos1', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos1/')),
                ('photos2', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos2/')),
                ('photos3', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos3/')),
                ('video1', models.FileField(blank=True, default='default_video.mp4', null=True, upload_to='farmer_videos1/')),
                ('photos4', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos4/')),
                ('photos5', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos5/')),
                ('photos6', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos6/')),
                ('description', models.TextField(default='Default description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Farm Title', max_length=200)),
                ('photos11', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='cow_photos/')),
                ('description', models.TextField(default='Default description')),
                ('photos12', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='cow_photos/')),
                ('video', models.FileField(blank=True, default='default_video.mp4', null=True, upload_to='cow_videos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='myfarm',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='myfarm',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='myfarm',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='myfarm',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='myfarm',
            name='photos1',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='cow_photos/'),
        ),
        migrations.AddField(
            model_name='myfarm',
            name='photos2',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='cow_photos/'),
        ),
        migrations.AddField(
            model_name='myfarm',
            name='photos3',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='cow_photos/'),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='title',
            field=models.CharField(default='Default Farm Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='video',
            field=models.FileField(blank=True, default='default_video.mp4', null=True, upload_to='cow_videos/'),
        ),
    ]
