# Generated by Django 5.1.6 on 2025-03-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_cow_farmer_producer_remove_myfarm_photo1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
