# Generated by Django 5.1.6 on 2025-03-16 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_delete_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Farm Title', max_length=200)),
                ('photos1', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos1/')),
                ('photos2', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos2/')),
                ('photos3', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos3/')),
                ('video1', models.FileField(blank=True, default='default_video.mp4', null=True, upload_to='farmer_videos1/')),
                ('photos4', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos4/')),
                ('photos5', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos5/')),
                ('photos6', models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='farmer_photos6/')),
                ('description', models.TextField(default='Default description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
