# Generated by Django 5.1.6 on 2025-03-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='farmer',
            name='description2',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='description3',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='description4',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='description5',
            field=models.TextField(default='Default description'),
        ),
    ]
